<?php
$className = Mage::getConfig()->getBlockClassName('megamenu/megamenu');
            $block = new $className();  
 $_menu = $block->renderCategoriesMenuHtml(0,'level-top') ?>

<nav class="nav-container">
        <?php if($_menu): ?>
            <div class="nav-mobilemenu-container visible-xs">
                <div class="navbar">
                        <div id="navbar-inner" class="navbar-inner navbar-inactive">
                                <div class="menu-mobile">
                                    <a style="float:left;" class="btn btn-navbar navbar-toggle">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                    </a>
                                    <!--<span class="brand navbar-brand"><?php echo $this->__('Menu') ?></span>-->
									<span class="brand navbar-brand">
									   <a href="/customer/account/"><img style="width: 21px;" src="https://www.ampow.com/media/wysiwyg/renyuan.png"></a>
									</span>
                                </div>
                                <ul id="nav-mobilemenu" class="mobilemenu nav-collapse collapse">
                                        <?php echo $_menu ?>
                                        <li class="blog level0 level-top"><a href="<?php echo $this->getUrl('blog')?>" class="level0" title="blog"><span><?php echo $this->__('Blog')?></span></a></li>
										   
                                </ul>
                        </div>
                </div>
            </div>
        <?php endif ?>
        <div id="nav_megamenu" class="nav_megamenu visible-lg visible-md">
            <?php $megamenu =  $this->getLayout()->createBlock('megamenu/megamenu'); ?>       
            <?php echo $megamenu->drawMegamenuHome(); ?>
            <?php //echo $megamenu->drawMegamenuMain(); ?>
            <div class="megamenu nav_product nav_newproduct">
                <div class="level-top"><a href="https://www.ampow.com/newproduct.html"><span><?php echo $this->__('New Arrivals') ?></span></a><span class="new"><?php echo $this->__('New')?></span></div>
              
            </div>
			
			
            
            <div class="megamenu nav_product nav_saleproduct">
                <div class="level-top"><a href="https://www.ampow.com/flashdeals.html"><span><?php echo $this->__('Flash Deals') ?></span></a><span class="hot"><?php echo $this->__('Hot')?></span></div>
               
            </div>
			
			
            <?php echo $megamenu->drawMegamenuLink(); ?>
            
            
        </div>
    <script type="text/javascript">
    var MEGAMENU_EFFECT = <?php echo (int)Mage::getStoreConfig('megamenu/general/effect')?>;
    jQuery(window).scroll(function () {
      if (jQuery(this).scrollTop() > 200) {
       jQuery('nav').addClass("fix-nav");
      } else {
       jQuery('nav').removeClass("fix-nav");
      }
    });
    </script>
</nav>
