<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner')->toHtml();?>

<div style="width: 100%;margin-top: -40px;">
<div style="width: 49%;float: left; margin-right: 1%;">
<a href="https://www.ampow.com/tattu-fpv-power-batteries.html"><img src="https://www.ampow.com/media/wysiwyg/banner-1.jpg" /></a>
</div>
<div style="width: 49%;float: right;">
<a href="https://www.ampow.com/gens-ace-rc-car-batteries.html"><img src="https://www.ampow.com/media/wysiwyg/banner-2.jpg" /></a>
</div>

</div>
