

<?php $_cartQty = $this->getSummaryCount() ?>
<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
          <!--<span class="top-cart-icon"></span>-->
                <div class="cart-mini-title">
                    <a class="shopping-cart" rel="nofollow" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">
                    <span class="cart-title"><span class="cart-title"><img src="https://www.ampow.com/media/wysiwyg/newcart.png" /><?php //echo $this->__('Cart:') ?></span>
                    <span class="cart-count"><?php //echo $_cartQty; ?><?php if($_cartQty<1) { echo $this->__('0 item -$0.00'); } else { echo $_cartQty; } ?></span>
                   <!--<span class="cart-qty"><?php //if($_cartQty<1) { echo $this->__('0'); } else { echo $_cartQty; } ?></span>-->
                   <span class="arrows"><i class="fa fa-arrow-right"></i></span>
                    </a>
                </div>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                    <?php else: ?>
					<img src="https://www.ampow.com/media/wysiwyg/cartimg.png" />
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            
                          <!--   <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button> -->

							<button type="button" style="    float: left;
    margin-right: 20px;" title="<?php echo $this->__('Cart') ?>" class="button" onclick="setLocation('https://www.ampow.com/checkout/cart/')"><span><span><?php echo $this->__('My Cart') ?></span></span></button>
                        </div>
                    <?php endif ?>
                </div>
            </div>

    </div>
</div>
<script type="text/javascript">
    var ajaxCartCfg = {
        'removeConfirm' : '<?php echo $this-> __('Are you sure you would like to remove this item ?') ?>',
    };
</script>
